version: "3.3"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME= MyFlaskApp
    expose:
      - 2020
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
